openapi: 3.0.1
info:
  title: WordTower API
  description: WordTower API
  contact: {}
  version: "1.0"
servers:
  - url: https://games-test.datsteam.dev
    description: Test server
  - url: https://games.datsteam.dev
    description: Production server
paths:
  /api/words:
    get:
      tags:
        - player
      summary: Words list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.PlayerExtendedWordsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
      security:
        - ApiKeyAuth: []
  /api/build:
    post:
      tags:
        - player
      summary: "Build tower or add words to existing tower. If tower is done, it will\
        \ be saved and you can start new tower"
      requestBody:
        description: "words, positions and directions"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/model.PlayerBuildRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.PlayerWordsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
      security:
        - ApiKeyAuth: []
      x-codegen-request-body-name: request
  /api/shuffle:
    post:
      tags:
        - player
      summary: Shuffle words list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.PlayerWordsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
      security:
        - ApiKeyAuth: []
  /api/towers:
    get:
      tags:
        - player
      summary: All  towers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/model.PlayerResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
      security:
        - ApiKeyAuth: []
  /api/rounds:
    get:
      tags:
        - player
      summary: game rounds
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/game.RoundListResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gamesdk.PublicError'
      security:
        - ApiKeyAuth: []
components:
  schemas:
    gamesdk.PublicError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    model.DoneTowerResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        score:
          type: number
          example: 1.0
    model.PlayerBuildRequest:
      type: object
      properties:
        done:
          type: boolean
        words:
          type: array
          items:
            $ref: '#/components/schemas/model.TowerWordRequest'
    model.PlayerExtendedWordsResponse:
      type: object
      properties:
        mapSize:
          example:
            - 30
            - 30
            - 100
          items:
            type: integer
          type: array
        nextTurnSec:
          type: integer
          example: 60
        roundEndsAt:
          type: string
          example: 2023-10-01T12:00:00Z
        shuffleLeft:
          type: integer
          example: 3
        turn:
          type: integer
          example: 1
        usedIndexes:
          type: array
          example:
            - 0
            - 1
            - 2
          items:
            type: integer
        words:
          type: array
          example:
            - word1
            - word2
            - word3
          items:
            type: string
    model.PlayerResponse:
      type: object
      properties:
        doneTowers:
          type: array
          items:
            $ref: '#/components/schemas/model.DoneTowerResponse'
        score:
          type: number
          example: 1.2
        tower:
          $ref: '#/components/schemas/model.PlayerTowerResponse'
    model.PlayerTowerResponse:
      type: object
      properties:
        score:
          type: number
          example: 1.2
        words:
          type: array
          items:
            $ref: '#/components/schemas/model.PlayerWord'
    model.PlayerWord:
      type: object
      properties:
        dir:
          type: integer
          example: 1
        pos:
          type: array
          example:
            - 0
            - 0
            - 0
          items:
            type: integer
        text:
          type: string
          example: word
    model.PlayerWordsResponse:
      type: object
      properties:
        shuffleLeft:
          type: integer
          example: 3
        words:
          type: array
          example:
            - word1
            - word2
            - word3
          items:
            type: string
    model.TowerWordRequest:
      type: object
      properties:
        dir:
          type: integer
          example: 1
        id:
          type: integer
          example: 0
        pos:
          type: array
          example:
            - 0
            - 0
            - 0
          items:
            type: integer
    game.RoundListResponse:
      type: object
      properties:
        eventId:
          type: string
          example: "1"
        now:
          type: string
          example: 2021-01-01T00:00:00Z
        rounds:
          type: array
          items:
            $ref: '#/components/schemas/game.RoundResponse'
    game.RoundResponse:
      type: object
      properties:
        duration:
          type: integer
          example: 60
        endAt:
          type: string
          example: 2021-01-01T00:00:00Z
        name:
          type: string
          example: Round 1
        repeat:
          type: integer
          example: 1
        startAt:
          type: string
          example: 2021-01-01T00:00:00Z
        status:
          type: string
          example: active
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-Auth-Token
      in: header
x-original-swagger-version: "2.0"
